name: Mirror to Codeberg

env:
  REPO_NAME: "${{ github.repository }}#*/"

on: [push]

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract repository name
        run: |
          # REPO_FULL_NAME="${{ github.repository }}"
          # REPO_NAME="${REPO_FULL_NAME#*/}.git"
          # export REPO_NAME=$REPO_NAME
          echo "Repo name extracted: $REPO_NAME"

      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: "https://codeberg.org/${{ secrets.GIT_USERNAME }}/${{ env.REPO_NAME }}"
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          PUSH_ALL_REFS: "true" # Push all branches
          DEBUG: "true"
