name: WakaTime
uses: lowlighter/metrics@latest
with:
  filename: metrics.wakatime.svg
  token: NOT_NEEDED
  base: ""
  plugin_wakatime: yes
  plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
  plugin_wakatime_days: 7
  plugin_wakatime_languages_other: no
  plugin_wakatime_repositories_visibility: public
  plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
